export const OPEN_STREAM_TYPE = 'open-stream';

export const DEFAULT_MAX_CONCURRENT_OPEN_STREAMS = 64;
export const DEFAULT_MAX_BUFFERED_CHUNKS_PER_STREAM = 64;
export const DEFAULT_MAX_BUFFERED_BYTES_PER_STREAM = 512 * 1024;
export const DEFAULT_OPEN_STREAM_IDLE_TIMEOUT_MS = 30_000;
export const DEFAULT_OPEN_STREAM_PROBE_TIMEOUT_MS = 10_000;
export const DEFAULT_OPEN_STREAM_CLOSE_GRACE_PERIOD_MS = 5_000;
